#!env/bin/python
import fire
from PyChain import Blockchain, request
import json


def getblocks(host: str):
    print(json.dumps(request(host, "get_blocks")["response"], indent=4))

def getblock(host: str, index: int):
    print(json.dumps(request(host, "get_block", index)["response"], indent=4))

def getpeers(host: str):
    print(request(host, "get_peers")["response"])

def getlength(host: str):
    print(request(host, "get_length")["response"])

def addpeer(host: str, host_to_add: str):
    print(request(host, "add_peer", host_to_add)["response"])



def addblock(host: str, data: str):
    print("Adding block to", "'", host, "'")
    blockchain = Blockchain()
    last_block = request(host, "get_block", -1)["response"]
    blockchain.import_chain([Blockchain.dict_to_block(last_block)])
    blockchain.add_block(data)
    print(request(host, "recieve_block",
          Blockchain.block_to_dict(blockchain.blocks[-1])))


if __name__ == '__main__':
    fire.Fire()
